# Basic dependabot.yml file with
# minimum configuration for one package managers

version: 2
updates:
  # Enable version updates for gradle
  - package-ecosystem: "gradle"
    directory: "/"
    schedule:
      interval: "weekly"
