name: 'CI'
on:
  push:
    branches: [ stable ]

jobs:
  release:
    if: startsWith(github.event.head_commit.message, 'patch: ') || startsWith(github.event.head_commit.message, 'minor: ') || startsWith(github.event.head_commit.message, 'major: ')
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v2
        
      - name: Bump patch and push tag
        id: tag_version
        uses: mathieudutour/github-tag-action@v5.6
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          tag_prefix: ""
          custom_release_rules: patch:patch,minor:minor,major:major
          default_bump: false
          release_branches: stable

      - name: "Build Changelog"
        id: github_release
        uses: mikepenz/release-changelog-builder-action@v2
        with:
          configuration: "config/configuration_repo.json"
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}

      - name: Create Release
        uses: softprops/action-gh-release@6034af24fba4e5a8e975aaa6056554efe4c794d0
        with:
          body: ${{steps.github_release.outputs.changelog}}
          prerelease: ${{ contains(github.ref, '-rc') || contains(github.ref, '-b') || contains(github.ref, '-a') }}
          tag_name: ${{steps.tag_version.outputs.new_tag}}
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}

