name: 'CI'
on:
  workflow_dispatch:

jobs:
  build_and_sign:
    runs-on: ubuntu-latest
    steps:  
        # Checks-out your repository under $GITHUB_WORKSPACE, so your job can access it
      - uses: actions/checkout@v2
        with:
          fetch-depth: 0

      - name: Decode Keystore
        env:
          ENCODED_STRING: ${{ secrets.KEYSTORE }}
          LOCAL_PROPERTIES: ${{ secrets.LOCAL_PROPERTIES }}
        run: |
            KEYSTORE_FILE_PATH="${GITHUB_WORKSPACE}"/app/keystore
            mkdir "${KEYSTORE_FILE_PATH}"
            echo $ENCODED_STRING | base64 -di > "${KEYSTORE_FILE_PATH}"/giua-app.jks
            echo $LOCAL_PROPERTIES >> "${GITHUB_WORKSPACE}"/local.properties
          
      - uses: gradle/wrapper-validation-action@v1

      - name: Set up JDK 11
        uses: actions/setup-java@v2
        with:
          java-version: '11'
          distribution: 'adopt'

      - uses: actions/cache@v2
        with:
          path: |
            ~/.gradle/caches
            ~/.gradle/wrapper
          key: ${{ runner.os }}-${{ github.job }}-${{ hashFiles('**/*.gradle*') }}-${{ hashFiles('**/gradle/wrapper/gradle-wrapper.properties') }}-${{ hashFiles('**/buildSrc/**/*.kt') }}
          restore-keys: |
            ${{ runner.os }}-${{ github.job }}-
          
      - name: Permission to gradle File
        run: chmod +x gradlew

      - name: Build release with Gradle
        run: ./gradlew assembleRelease
        env:
          SIGNING_KEY_ALIAS: ${{ secrets.SIGNING_KEY_ALIAS }}
          SIGNING_KEY_PASSWORD: ${{ secrets.SIGNING_KEY_PASSWORD }}
          SIGNING_STORE_PASSWORD: ${{ secrets.SIGNING_STORE_PASSWORD }}


      - uses: actions/upload-artifact@v2
        with:
          name: apk_signed
          path: app/build/outputs/apk/release/app-release.apk
